version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DB_TYPE: mssql
      DB_HOST: mssql
      DB_PORT: 1433
      DB_USERNAME: sa
      DB_PASSWORD: "Huy19082004@"
      DB_DATABASE: ecommerce
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: ecommserse
      KEYCLOAK_CLIENT_ID: express-api
      
    depends_on:
      mssql:
        condition: service_healthy
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    ports:
      - "8080:8080"
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mssql
      KC_DB_URL_HOST: mssql
      KC_DB_URL_PORT: 1433
      KC_DB_URL: "jdbc:sqlserver://mssql:1433;databaseName=ecommerce;encrypt=false;trustServerCertificate=true"
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: "Huy19082004@"
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      QUARKUS_DATASOURCE_XA_ENABLED: "false"
      KC_TRANSACTION_XA_ENABLED: "false"
    

    depends_on:
      mssql:
        condition: service_healthy
    restart: unless-stopped

  mssql:
    build:
      context: .
      dockerfile: Dockerfile.mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Huy19082004@"
      ACCEPT_EULA: "Y"
    volumes:
      - ./init:/init
    command: /bin/bash /init/entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"Huy19082004@\" || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
    restart: unless-stopped
