services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    ports:
      - "8080:8080"
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
#      KEYCLOAK_DATABASE_VENDOR: mssql
#      KC_DB: dev-file

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "12345"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_TYPE: mssql
      DB_HOST: mssql
      DB_PORT: 1433
      DB_USERNAME: sa
      DB_PASSWORD: P@ssw0rd
      DB_NAME: ecommerce
      DB_SYNCHRONIZE: "true"
      DB_LOGGING: "true"
      DB_ENCRYPT: "false"
      SECRET: app_secret
    depends_on:
      - mssql
      - keycloak
    command: bash -c "npm install && npm run build && npm run start"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: bash -c "npm install && npm run build && npm run preview"

volumes:
  mssql_data:
